### ISSUE TITLE
Can not connect to  a db on a local docker container from a jupyter notebook running on same local docker.

### ISSUE THREAD

**Issue by kyokonishito** [IBM/db2-jupyter#3]
I can not connect to a db2 on a local docker container in my local machine (Mac) from a jupyter notebook running on same local docker.
Because when I set the host  value as `host.docker.internal`,  db2.ipynb converts the host to upper case characters, `HOST.DOCKER.INTERNAL`.  It should be lowercase to connect. I'm not sure why upper case conversion is required for HOST value.

```sh
%sql CONNECT TO sample USER db2inst1 USING xxxxx HOST host.docker.internal PORT 50000
```
Error message:
```
SQL1336N The remote host "HOST.DOCKER.INTERNAL" was not found. SQLSTATE=08001 SQLCODE=-1336
```

Is it possible to remove `upper()` at line 85 in the cell of `def parseConnect(inSQL,local_ns):`?   Then the host value is same as input. When I used the updated code,  I could connect the db successfully.

Current
```python
         elif cParms[cnt].upper() == 'HOST':
            if cnt+1 < len(cParms):
                hostport = cParms[cnt+1].upper() ##remove upper()
                ip, port = split_string(hostport)
                if (port == None): _settings["port"] = "50000"
                _settings["hostname"] = ip
                cnt = cnt + 1
```

Updated
```python
         elif cParms[cnt].upper() == 'HOST':
            if cnt+1 < len(cParms):
                hostport = cParms[cnt+1]  ## upper() is removed
                ip, port = split_string(hostport)
                if (port == None): _settings["port"] = "50000"
                _settings["hostname"] = ip
                cnt = cnt + 1
```

**Comment by kyokonishito** [comment]
I create a pull request for this isuue:  https://github.com/IBM/db2-jupyter/pull/4

**Comment by baklarz** [comment]
I have updated the code to include the fix above. In addition, the documentation has been extensively updated and now available at the [Db2 Magic Commands](https://github.com/IBM/db2-jupyter) website. Thanks for tracking down the issue.
