### ISSUE TITLE
Connecting using SSL

### ISSUE THREAD

**Issue by fdiazluque** [IBM/db2-jupyter#6]
Hi team,

I am trying to connect to a DB2 database in IBM Cloud, from a local Jypiter notebook.
Please, could you help me to build the CONNECT sentence using SSL?

Based on db2.ipynb, it should be something like:
`%sql CONNECT TO SAMPLE USER DB2INST1 USING db2inst1 SSL <filename>`

but whatever the format I use for the file path, I get the error:
`CLI0157E Error opening a file. SQLSTATE=HY507 SQLCODE=-99999`

Notes:
Jupyter notebook: 6.4.5
ibm-db 3.1.0

**Comment by baklarz** [comment]
Code was tested against Db2 Cloud and connected successfully. Not sure if a missing HOST and PORT setting may have resulted in the failure. Syntax should have been:
`%sql CONNECT TO SAMPLE USER DB2INST1 USING db2inst1 HOST xxxx PORT 50001 SSL /this/is/my/file`
